apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "kubernetes.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kubernetes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  updateStrategy:
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: {{ template "kubernetes.name" . }}
    spec:
      nodeSelector:
        {{- range $key, $val := .Values.traefikNodeSelector }}
        {{ $key }}: {{ $val | quote }}
        {{- end}}
      serviceAccountName: {{ template "kubernetes.name" . }}
      terminationGracePeriodSeconds: 3600
      hostNetwork: true
      initContainers:
      - name: {{ template "kubernetes.name" . }}-bootstrap
        image: quay.io/mysocialapp/docker-traefik-bootstrap-ha:{{ .Values.traefikImageVersion }}
        command:
          - "/bin/sh"
          - "-c"
          - "cat /etc/traefik/resolv.conf > /etc/resolv.conf ; /bin/sh -c /traefik-scripts/bootstrap.sh"
        volumeMounts:
        - name: traefik-config
          mountPath: /etc/traefik
        - name: traefik-scripts
          mountPath: /traefik-scripts
      containers:
      - name: {{ template "kubernetes.name" . }}
        image: quay.io/mysocialapp/docker-traefik-bootstrap-ha:{{ .Values.traefikImageVersion }}
        command:
          - "/bin/sh"
          - "-c"
          - "cat /etc/traefik/resolv.conf > /etc/resolv.conf ; /entrypoint.sh --consul --consul.endpoint={{ .Values.traefikConsulServiceName }}:8500"
        env:
        - name: CLOUDFLARE_EMAIL
          valueFrom:
            secretKeyRef:
              name: externaldns
              key: cloudflare.api.email
        - name: CLOUDFLARE_API_KEY
          valueFrom:
            secretKeyRef:
              name: externaldns
              key: cloudflare.api.key
        {{ if .Values.traefikCloudflareDnsUpdate }}
        lifecycle:
          postStart:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - |
                {{- range $rrdns, $zoneid := .Values.traefikCloudflareDnsUpdate }}
                /traefik-scripts/lifecycle.sh start {{ $zoneid | quote}} {{ $rrdns | quote }}
                {{- end}}
          preStop:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - |
                {{- range $rrdns, $zoneid := .Values.traefikCloudflareDnsUpdate }}
                /traefik-scripts/lifecycle.sh stop {{ $zoneid | quote}} {{ $rrdns | quote }}
                {{- end}}
        {{ end }}
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
        ports:
        - name: http
          hostPort: 80
          containerPort: 80
        - name: https
          hostPort: 443
          containerPort: 443
        - name: admin
          containerPort: 8081
        securityContext:
          privileged: true
        volumeMounts:
        - name: traefik-config
          mountPath: /etc/traefik
        - name: traefik-scripts
          mountPath: /traefik-scripts
      volumes:
      - name: traefik-config
        configMap:
          name: {{ template "kubernetes.name" . }}
      - name: traefik-scripts
        configMap:
          name: {{ template "kubernetes.name" . }}-scripts
          defaultMode: 0775